#!/bin/bash
rm -rf logs/*
g++ launcher.cpp -pthread --std=c++1z

for (( ID=1; ID <= 1000; ID++ )) do echo $ID; done | xargs -I{} --max-procs 20 bash -c "
echo 'start solution: '{}; ./a.out {} 2> logs/{}.log; echo 'finished solution: '{}; tail -n 2 logs/{}.log; exit 1;"
echo "exit code for xargs = $?"
