#!/bin/bash
rm -rf logs/*
g++ launcher.cpp -pthread --std=c++1z

IDS=(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20)
for ID in ${IDS[*]}; do echo $ID; done | xargs -I{} --max-procs 8 bash -c "
echo 'start solution: '{}; ./a.out {} 2> logs/{}.log; echo 'finished solution: '{}; exit 1;"
echo "exit code for xargs = $?"
