#!/bin/bash
rm -rf logs/*
g++ launcher.cpp -pthread --std=c++1z -O2

for (( ID=1; ID <= 1000; ID++ )) do echo $ID; done | xargs -I{} -P 8 bash -c "
echo 'start solution: '{}; ./a.out {} <<test_name>> 2> logs/<<test_name>>_{}.log; echo 'finished solution: '{}; tail -n 2 logs/<<test_name>>_{}.log; exit 1;"
echo "exit code for xargs = $?"
