#!/bin/bash
rm -rf logs/*
mkdir logs
g++ launcher.cpp --std=c++1z

for (( ID=1; ID <= 1000; ID++ )) do echo $ID; done | xargs -I {} -P 8 bash -c "
echo 'start solution: '{}; ./a.out {} 2> logs/{}.log; echo 'finished solution: '{}; tail -n 2 logs/{}.log; exit 1;"
echo "exit code for xargs = $?"
