#!/bin/bash -e
rm -rf logs/*
g++ launcher.cpp -pthread --std=c++1z -O2

find ../../input -name "*.in" -exec basename {} .in ';' | xargs -I {} -P 8 bash -c "
echo 'start solution for test: '{};
./a.out 0 {} 2> logs/{}.log;
echo 'finished test: '{};
tail -n 2 logs/{}.log;
exit 1;"
